# Generated by Django 2.2.5 on 2019-11-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191102_0051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleImage',
            new_name='Image',
        ),
    ]
