# Generated by Django 2.2.5 on 2019-11-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191102_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ArticleImage',
        ),
    ]
