# Generated by Django 2.2.5 on 2019-11-02 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191102_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата комментария'),
        ),
    ]
